//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("VRUtilityBelt")]
[assembly: System.Reflection.AssemblyCompany("Fennec Labs Ltd")]
[assembly: System.Reflection.AssemblyCopyright("© 2017 Fennec Labs Ltd")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1.6491#4135437")]
[assembly: System.Reflection.AssemblyVersion("0.1.6491")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.6491")]


